% ftp_v1
% Script containing my first implementation of the Fourier Tranform
% Profilometry algorithm outlined by Cobelli et al (2009)

% read in data, taken with camera and croppod or generated by 
% generateTestPair script
refim = imread('refim.png');
dataim = imread('dataim.png');